
GET http://localhost:4000/
/// js
POST http://localhost:3000/products
///bdb
GET http://localhost:3000/products
///bdb
PATCH http://localhost:3000/products
///bdb
DELETE http://localhost:3000/products
///bdb
GET http://localhost:3000/abc_xyz